CREATE TABLE currency_info
(
    id            INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code          VARCHAR(255)                         NOT NULL,
    chinese_alias VARCHAR(255)                         NOT NULL,
    CONSTRAINT pk_currency_info PRIMARY KEY (id)
);

ALTER TABLE currency_info
    ADD CONSTRAINT uc_currency_info_code UNIQUE (code);

CREATE INDEX idx_de603fc194510b238b4f55bad ON currency_info (code);